export const ON_CHANGE_DATA_TEST_SUCCESS = 'ON_CHANGE_DATA_TEST_SUCCESS'
export const ON_FETCH_DATA_SUCCESSED = 'ON_FETCH_DATA_SUCCESSED'
export const ON_FETCH_DATA_REQUESTED = 'ON_FETCH_DATA_REQUESTED'
export const ON_FETCH_DATA_FAILED = 'ON_FETCH_DATA_FAILED'
export const ON_SIGN_UP_USER_SUCCESSED = 'ON_SIGN_UP_USER_SUCCESSED'
export const ON_SIGN_UP_USER_REQUESTED = 'ON_SIGN_UP_USER_REQUESTED'
export const ON_SIGN_UP_USER_FAILED = 'ON_SIGN_UP_USER_FAILED'

export const ON_LOGIN_USER_SUCCESSED='ON_LOGIN_USER_SUCCESSED'
export const ON_LOGIN_USER_REQUESTED='ON_LOGIN_USER_REQUESTED'
export const ON_LOGIN_USER_FAILED='ON_LOGIN_USER_FAILED'

export const ON_LOGOUT_USER_REQUESTED='ON_LOGOUT_USER_REQUESTED'

export const ON_SCENE_CHANGE_REQUESTED='ON_SCENE_CHANGE_REQUESTED';
